{{- if .Values.ingress.use }}
apiVersion: v1
kind: Service
metadata:
  labels:
    csc: {{ .Release.Name }}
  name: {{ .Release.Name }}-service
  namespace: {{ .Values.csc.namespace }}
spec:
  ports:
  - port: 8000
    targetPort: 8000
  selector:
    csc: {{ .Release.Name }}
  type: ClusterIP
{{- end }}
