apiVersion: v1
kind: Service
metadata:
  labels:
    csc: ccheaderservice
  name: ccheaderservice-service
  namespace: maintel
spec:
  ports:
  - port: 8000
    targetPort: 8000
  selector:
    csc: ccheaderservice
  type: ClusterIP
