csc:
  image:
    repository: ts-dockerhub.lsst.org/scheduler
    tag: c0022
    pullPolicy: Always
    nexus3: nexus3-docker
  env:
    LSST_DDS_PARTITION_PREFIX: ncsa
    S3_ENDPOINT_URL: http://lsst-l1-cl-header.ncsa.illinois.edu:9000
  envSecrets:
  - name: AWS_ACCESS_KEY_ID
    secretName: lfa
    secretKey: aws-access-key-id
  - name: AWS_SECRET_ACCESS_KEY
    secretName: lfa
    secretKey: aws-secret-access-key
  - name: MYS3_ACCESS_KEY
    secretName: lfa
    secretKey: aws-access-key-id
  - name: MYS3_SECRET_KEY
    secretName: lfa
    secretKey: aws-secret-access-key
  shmemDir: /scratch.local/ospl
  osplVersion: V6.10.4
  nfsMountpoint:
  - name: rubin-sim-data
    containerPath: /home/saluser/rubin_sim_data
    readOnly: true
    server: lsst-l1-cl-arctl.ncsa.illinois.edu
    serverPath: /project/scheduler
