# Deployment at NCSA is handled by docker-compose for M2
# This is here as an emergency
csc:
  image:
    repository: ts-dockerhub.lsst.org/m2
    tag: c0015
    pullPolicy: Always
    nexus3: nexus3-docker
  env:
    LSST_DDS_PARTITION_PREFIX: ncsa
