csc:
  image:
    repository: ts-dockerhub.lsst.org/m2
    tag: c0022
    pullPolicy: Always
    nexus3: nexus3-docker
  env:
    LSST_DDS_PARTITION_PREFIX: base
    RUN_ARG: --simulate
  shmemDir: /run/ospl
