love-manager:
  image:
    repository: ts-dockerhub.lsst.org/love-manager
    tag: c0023
    pullPolicy: IfNotPresent
    nexus3: nexus3-docker
  secret_path: tucson-teststand.lsst.codes
  env:
    SERVER_URL: love.tu.lsst.org
    REDIS_CONFIG_EXPIRY: 5
    REDIS_CONFIG_CAPACITY: 5000
  autoscaling:
    enabled: false
    targetCPUUtilizationPercentage: 50
  database:
    image:
      repository: postgres
      tag: '12.0'
      pullPolicy: IfNotPresent
    storage:
      name: love-manager-database
      path: /var/lib/postgresql
      storageClass: rook-ceph-block
      accessMode: ReadWriteOnce
      claimSize: 2Gi
  redis:
    image:
      repository: redis
      tag: 5.0.3
      pullPolicy: IfNotPresent
