csc:
  image:
    repository: ts-dockerhub.lsst.org/mtaos_sim
    tag: c0017
    pullPolicy: Always
    nexus3: nexus3-docker
  env:
    LSST_DDS_PARTITION_PREFIX: ncsa
    RUN_ARG: --simulate
  shmemDir: /scratch.local/ospl
  nfsMountpoint:
    - name: lsstdata
      containerPath: /lsstdata/offline/teststand
      readOnly: true
      server: lsst-nfs.ncsa.illinois.edu
      serverPath: /offline/teststand
