csc:
  image:
    repository: ts-dockerhub.lsst.org/mtaos
    tag: c0018
    pullPolicy: Always
    nexus3: nexus3-docker
  env:
    LSST_DDS_PARTITION_PREFIX: ncsa
  shmemDir: /scratch.local/ospl
  nfsMountpoint:
  - name: lsstdata
    containerPath: /lsstdata/offline/teststand
    readOnly: true
    server: lsst-nfs.ncsa.illinois.edu
    serverPath: /offline/teststand
  - name: project-shared
    containerPath: /project
    readOnly: false
    server: lsst-l1-cl-arctl.ncsa.illinois.edu
    serverPath: /project
