csc:
  image:
    repository: ts-dockerhub.lsst.org/mtaos
    tag: c0022
    pullPolicy: Always
    nexus3: nexus3-docker
  env:
    LSST_DDS_PARTITION_PREFIX: summit
  shmemDir: /run/ospl
  nfsMountpoint:
  - name: comcam-gen3-data
    containerPath: /repo/LSSTComCam
    readOnly: false
    server: comcam-arctl01.cp.lsst.org
    serverPath: /repo/LSSTComCam
  - name: comcam-gen3-data-temp
    containerPath: /data/lsstdata/base/comcam
    readOnly: true
    server: comcam-arctl01.cp.lsst.org
    serverPath: /lsstdata/base/comcam
  - name: comcam-data
    containerPath: /readonly/lsstdata/comcam
    readOnly: true
    server: comcam-arctl01.cp.lsst.org
    serverPath: /lsstdata
  - name: project-shared
    containerPath: /project
    readOnly: false
    server: nfs1.cp.lsst.org
    serverPath: /project
  osplVersion: V6.10.4
