csc:
  image:
    repository: ts-dockerhub.lsst.org/atdometrajectory
    tag: c0019
    pullPolicy: Always
    nexus3: nexus3-docker
  env:
    LSST_DDS_PARTITION_PREFIX: summit
  shmemDir: /run/ospl
  osplVersion: V6.11.0
