spec:
  destination:
    # -- The URL for the Kubernetes server
    server: https://kubernetes.default.svc
  source:
    # -- The repository URL that contains the configuration
    repoURL: https://github.com/lsst-ts/argocd-csc
    # -- The target revision (repository branch) to use for the configuration
    targetRevision: HEAD
# -- The list of applications for the LOVE service
apps:
  - love-commander
  - love-manager
  - love-nginx
  - love-producer
# -- The environment (location) to set for the configuration.
# This picks the Helm values file to use in the deployment.
env:
