csc:
  image:
    repository: ts-dockerhub.lsst.org/scriptqueue
    tag: c0021
    pullPolicy: Always
    nexus3: nexus3-docker
  env:
    LSST_DDS_PARTITION_PREFIX: ncsa
    RUN_ARG: 1
  shmemDir: /scratch.local/ospl
  nfsMountpoint:
  - name: auxtel-gen2
    containerPath: /project/shared/auxTel
    readOnly: false
    server: lsst-l1-cl-arctl.ncsa.illinois.edu
    serverPath: /project/shared/auxTel
  - name: gen3
    containerPath: /repo
    readOnly: false
    server: lsst-l1-cl-arctl.ncsa.illinois.edu
    serverPath: /repo
  osplVersion: V6.10.4
