vaultPathPrefix: secret/k8s_operator/tucson-teststand.lsst.codes
secrets:
  - name: nexus3-docker
    key: pull-secret
    type: kubernetes.io/dockerconfigjson
    namespaces:
      - namespaces
      - uws
  - name: lfa
    key: ts/software/lfa
    namespaces:
      - auxtel
      - love
      - maintel
      - obssys
  - name: ts-salkafka
    key: ts-salkafka-password
    namespaces:
      - kafka-producers
