cluster-config:
  vaultPathPrefix: secret/k8s_operator/lsst-nts-k8s.ncsa.illinois.edu
  secrets:
    - name: nexus3-docker
      key: ts/software/nexus3-docker
      type: kubernetes.io/dockerconfigjson
      namespaces:
        - namespaces
        - uws
    - name: lfa
      key: ts/software/lfa
      namespaces:
        - obssys
