vaultPathPrefix: secret/k8s_operator/base-lsp.lsst.codes
secrets:
  - name: nexus3-docker
    key: pull-secret
    type: kubernetes.io/dockerconfigjson
    namespaces:
      - namespaces
      - uws
  - name: lfa
    key: ts/software/lfa
    namespaces:
      - auxtel
      - calsys
      - maintel
      - obssys
  - name: ts-salkafka
    key: ts/software/ts-salkafka
    namespaces:
      - kafka-producers
  - name: butler-secret
    key: butler-secret
    namespaces:
      - maintel
      - obssys
