csc:
  image:
    repository: ts-dockerhub.lsst.org/watcher
    tag: c0026
    pullPolicy: Always
    nexus3: nexus3-docker
  env:
    RUN_ARG: --state enabled
    LSST_DDS_PARTITION_PREFIX: tucson
    LSST_SITE: tucson
  shmemDir: /run/ospl
  osplVersion: V6.10.4
