csc:
  image:
    repository: ts-dockerhub.lsst.org/weatherstation
    tag: c0025
    pullPolicy: Always
    nexus3: nexus3-docker
  env:
    LSST_DDS_PARTITION_PREFIX: tucson
    LSST_SITE: tucson
  shmemDir: /run/ospl
  osplVersion: V6.10.4
ingress:
  use: false
