csc:
  image:
    repository: ts-dockerhub.lsst.org/headerservice
    tag: ts-v2.9.1_salobj_v6.4.1_idl_v3.1.3_xml_v9.1.1_c0021
    pullPolicy: Always
    nexus3: nexus3-docker
  env:
    LSST_DDS_PARTITION_PREFIX: summit
    LSST_DDS_RESPONSIVENESS_TIMEOUT: 15s
    IP_HEADERSERVICE: atheaderservice.cp.lsst.org
    URL_SPEC: --url_format http://{ip_address}/{filename_HDR}
    PORT_SPEC: --port_number 8008
  pvcMountpoint:
  - name: www
    path: /home/saluser/www
    accessMode: ReadWriteOnce
    claimSize: 50Gi
  shmemDir: /run/ospl
  osplVersion: V6.10.4
ingress:
  use: true
  hostname: atheaderservice.cp.lsst.org
  port: 8008
