image:
  repository: ts-dockerhub.lsst.org/genericcamera
  tag: c0026
  pullPolicy: Always
  nexus3: nexus3-docker
env:
  LSST_DDS_PARTITION_PREFIX: tucson
  LSST_SITE: tucson
  OSPL_INFOFILE: /tmp/ospl-info-genericcamera.log
  OSPL_ERRORFILE: /tmp/ospl-error-genericcamera.log
shmemDir: /run/ospl
osplVersion: V6.10.4
service:
  use: true
  port: 5013
