spec:
  destination:
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/lsst-ts/argocd-csc
    targetRevision: HEAD

env: ncsa-teststand

cscs:
  - ataos
  - atdome
  - atdometrajectory
  - athexapod
  - atmcs
  - atpneumatics
  - atptg
  - hexapodsim
  - atspectrograph

noSim:
  - ataos
