env: tucson-teststand
cscs:
  - ataos
  - atdome
  - atdometrajectory
  - atheaderservice
  - athexapod
  - atptg
  - atspectrograph
  - hexapodsim
spec:
  source:
    targetRevision: tickets/DM-30329
