csc:
  image:
    repository: ts-dockerhub.lsst.org/athexapod
    tag: c0010
    pullPolicy: Always
    nexus3: nexus3-docker

  env:
    LSST_DDS_DOMAIN: ncsa
    OSPL_INFOFILE: /tmp/ospl-info-athexapod.log
    OSPL_ERRORFILE: /tmp/ospl-error-athexapod.log

  osplVersion: V6.10.4
  shmemDir: /scratch.local/ospl
