csc:
  image:
    repository: ts-dockerhub.lsst.org/mtdome
    tag: c0026
    pullPolicy: Always
    nexus3: nexus3-docker
  env:
    LSST_DDS_PARTITION_PREFIX: summit
    LSST_SITE: summit
    RUN_ARG: --simulate
  shmemDir: /run/ospl
  osplVersion: V6.10.4
