{{- if .Values.redis.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  internalTrafficPolicy: Cluster
  selector:
    app.kubernetes.io/instance: {{ include "rapid-analysis.redis.fullname" . }}
  ports:
  - name: redis
    protocol: TCP
    port: {{ .Values.redis.port }}
    targetPort: {{ .Values.redis.port }}
{{- end }}
