---
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: pull-secret
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ include "rapid-analysis.name" . }}
spec:
  path: {{ required "vaultPrefixPath must be set" .Values.vaultPrefixPath }}/{{ required "pullSecretsPath must be set" .Values.pullSecretsPath }}
  type: kubernetes.io/dockerconfigjson
---
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: google-creds
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ include "rapid-analysis.name" . }}
spec:
  path: {{ required "vaultPrefixPath must be set" .Values.vaultPrefixPath }}/{{ required "credentialSecretsPath must be set" .Values.credentialSecretsPath }}
  type: Opaque
---
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: butler-secret
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ include "rapid-analysis.name" . }}
spec:
  path: {{ required "vaultPrefixPath must be set" .Values.vaultPrefixPath }}/{{ required "butlerSecret.key must be set" .Values.butlerSecret.key }}
  type: Opaque
---
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: rubintv-secrets
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ include "rapid-analysis.name" . }}
spec:
  path: {{ required "vaultPrefixPath must be set" .Values.vaultPrefixPath }}/{{ required "rubinTvSecretsPath must be set" .Values.rubinTvSecretsPath }}
  type: Opaque
