{{- $protectedApps := list "mtm2" "mtm1m3" }}
{{- range $csc := .Values.cscs }}
{{- $cscn := "" }}
{{- if hasKey $.Values.renameMap $csc }}
{{- $cscn = get $.Values.renameMap $csc }}
{{- else }}
{{- $cscn = $csc }}
{{- end }}
{{- $app := "" }}
{{- $isIndexed := false }}
{{- $checkForIndex := list }}
{{- if not (has $csc $protectedApps) }}
{{- $checkForIndex = regexFindAll "[0-9]+$" $csc -1 }}
{{- end }}
{{- if $checkForIndex }}
{{- $isIndexed = true }}
{{- $index := first $checkForIndex }}
{{- $app = regexReplaceAll $index $csc "" }}
{{- else }}
{{- $app = $csc }}
{{- end }}
{{- if has $csc $.Values.isSim }}
{{- $cscn = list $cscn "sim" | join "-" }}
{{- $csc = list $csc "sim" | join "-" }}
{{- end }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $cscn }}
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: {{ $.Values.namespace }}
    server: {{ $.Values.spec.destination.server }}
  project: default
  source:
    path: apps/{{ $app }}
    repoURL: {{ $.Values.spec.source.repoURL }}
    targetRevision: {{ $.Values.spec.source.targetRevision }}
    helm:
      valueFiles:
        {{- if $isIndexed }}
        - values-{{ $csc }}.yaml
        {{- end }}
        - values-{{ $.Values.env }}.yaml
{{ end }}
