love-nginx:
  image:
    repository: nginx
    tag: 1.13.1
    pullPolicy: IfNotPresent
  ingress:
    hostname: lsst-love-nts.ncsa.illinois.edu
  config: |
    server {
      listen 80;
      server_name localhost;
      location / {
        root   /usr/src/love-frontend;
        try_files $uri$args $uri$args/ $uri/ /index.html;
      }
      location /manager {
          proxy_pass http://love-manager-service:8000;
          proxy_http_version 1.1;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection "upgrade";
          proxy_set_header Host $host;
          proxy_redirect off;
      }
      location /manager/static {
          alias /usr/src/love-manager/manager/static;
      }
      location /manager/media {
          alias /usr/src/love-manager/manager/media;
      }
    }
  pvcMountpoint:
  - name: love-frontend
    path: /usr/src/love-frontend
    storageClass: local-path
    accessMode: ReadWriteOnce
    claimSize: 1Gi
  - name: love-manager
    path: /usr/src/love-manager
    storageClass: local-path
    accessMode: ReadWriteOnce
    claimSize: 1Gi
