love-nginx:
  image:
    repository: nginx
    tag: 1.13.1
    pullPolicy: IfNotPresent
  ingress:
    hostname: lsst-love-nts.ncsa.illinois.edu
  initContainers:
    frontend:
      image:
        repository: lsstts/love-frontend
        tag: c0018.000
    manager:
      image:
        repository: lsstts/love-manager
        tag: c0018.000
      command: [ "/bin/sh", "-c", "mkdir -p /usr/src/love-manager/media/thumbnails; mkdir -p /usr/src/love-manager/media/configs; cp -Rv /usr/src/love/manager/static /usr/src/love-manager; ls -lhR /; cp -uv /usr/src/love/manager/ui_framework/fixtures/thumbnails/* /usr/src/love-manager/media/thumbnails; cp -uv /usr/src/love/manager/api/fixtures/configs/* /usr/src/love-manager/media/configs" ]
  staticStore:
    name: love-nginx-static
    storageClass: local-path
    accessMode: ReadWriteOnce
    claimSize: 2Gi
