apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
  name: {{ .Release.Name }}
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - port: 50000
    targetPort: 50000
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
  type: ClusterIP
