apiVersion: v1
kind: Service
metadata:
  labels:
    csc: {{ .Release.Name }}
  name: {{ .Release.Name }}
  namespace: {{ .Values.csc.namespace }}
spec:
  ports:
  - port: 50000
    targetPort: 50000
  selector:
    csc: {{ .Release.Name }}
  type: ClusterIP
