apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ocps-uws-job
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: ocps-uws-job
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: services/ocps-uws-job
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
