kafka-producers:
  image:
    repository: ts-dockerhub.lsst.org/salkafka
    tag: c0011
    pullPolicy: Always
    nexus3: nexus3-docker
  env:
    lsstDdsDomain: ncsa
    brokerIp: cp-helm-charts-cp-kafka-headless.cp-helm-charts
    brokerPort: 9092
    registryAddr: http://cp-helm-charts-cp-schema-registry.cp-helm-charts:8081
    partitions: 1
    replication: 3
    waitAck: 1
    logLevel: 20
  osplVersion: V6.10.4
  shmemDir: /scratch.local/ospl
  producers:
    auxtel:
      env:
        lsstDdsDomain: ncsa.obs.at.cs
    comcam:
      env:
        lsstDdsDomain: ncsa.obs.mt.comcam
    eas: null
    latiss:
      env:
        lsstDdsDomain: ncsa.obs.at.latiss
    maintel:
      env:
        lsstDdsDomain: ncsa.obs.mt.cs
    mtmount:
      env:
        lsstDdsDomain: ncsa.obs.mt.cs.mount
    m1m3:
      env:
        lsstDdsDomain: ncsa.obs.mt.cs.m1m3
        partitions: 3
    m2:
      env:
        lsstDdsDomain: ncsa.obs.mt.cs.m2
        partitions: 3
    obssys:
      env:
        lsstDdsDomain: ncsa.obs
    test:
      env:
        lsstDdsDomain: ncsa.obs
