kafka-producers:
  image:
    repository: ts-dockerhub.lsst.org/salkafka
    tag: c0015
    pullPolicy: Always
    nexus3: nexus3-docker
  env:
    lsstDdsPartitionPrefix: summit
    brokerIp: kafka-0-summit-efd.lsst.codes
    brokerPort: 31090
    registryAddr: https://schema-registry-summit-efd.lsst.codes
    partitions: 1
    replication: 3
    waitAck: 1
    logLevel: 20
    extras:
      LSST_DDS_RESPONSIVENESS_TIMEOUT: 15s
  shmemDir: /run/ospl
