kafka-producers:
  image:
    repository: lsstts/salkafka
    tag: v1.1.2_salobj_v5.11.0_xml_v5.1.0
    pullPolicy: Always

  env:
    lsstDdsDomain: ncsa
    brokerIp: cp-helm-charts-cp-kafka-headless.cp-helm-charts
    brokerPort: 9092
    registryAddr: https://lsst-schema-registry-nts-efd.ncsa.illinois.edu
    partitions: 1
    replication: 3
    logLevel: 10

  producers:
    auxtel: null
    eas: null
    latiss: null
    test: null
