kafka-producers:
  image:
    repository: lsstts/salkafka
    tag: v1.1.1_salobj_v5.10.0_xml_v5.0.0
    pullPolicy: Always
  env:
    lsstDdsDomain: sandboxtest
    brokerIp: cp-helm-charts-cp-kafka-headless.cp-helm-charts
    brokerPort: 9092
    registryAddr: https://schema-registry-sandbox-efd.lsst.codes
    partitions: 1
    replication: 3
    waitAck: 1
    logLevel: 20

  producers:
    maintel: null
    mtmount: null
    comcam: null
    obssys: null
    eas:
      cscs: >-
        DSM
        Test
    m1m3:
      cscs: >-
        MTM1M3
        MTAOS
    test: null
