kafka-producers:
  image:
    repository: lsstts/salkafka
    tag: v1.1.1_salobj_v5.10.0_xml_v5.0.0
    pullPolicy: Always

  env:
    lsstDdsDomain: ncsa
    brokerIp: lsst-kafka-0-nts-efd.ncsa.illinois.edu
    brokerPort: 31090
    registryAddr: https://lsst-schema-registry-nts-efd.ncsa.illinois.edu
    partitions: 1
    replication: 3
    logLevel: 10

  producers:
    eas: null
    latiss:
    m1m3:
      cscs: >-
        MTVMS
        MTM1M3
        MTPtg
        MTAOS
    m2:
    obssys: null
    test: null
