kafka-producers:
  image:
    repository: lsstts/salkafka
    tag: v1.1.0_salobj_v5.7.0_xml_4.8.0
    pullPolicy: Always
  env:
    lsstDdsDomain: sandboxtest
    brokerIp: cp-helm-charts-cp-kafka-headless.cp-helm-charts
    brokerPort: 9092
    registryAddr: https://schema-registry-sandbox-efd.lsst.codes
    partitions: 1
    replication: 3
    logLevel: 20

  producers:
    comcam: null
    obssys: null
    m1m3:
      cscs: >-
        MTM1M3
        MTAOS
