kafka-producers:
  image: 
    repository: lsstts/salkafka
    tag: v1.1.0_salobj_v5.4.0_xml_v4.7.0
    pullPolicy: Always

  env:
    lsstDdsDomain:
      auxtel: lsatmcs
      eas: lsatmcs
      latiss: lsatmcs
      m1m3: m1m3Test213
      m2: m2
      obssys: lsatmcs
      default: summit
    brokerIp: kafka-0-summit-efd.lsst.codes
    brokerPort: 31090
    registryAddr: https://schema-registry-summit-efd.lsst.codes
    logLevel: 10
