kafka-producers:
  image:
    repository: ts-dockerhub.lsst.org/salkafka
    tag: c0025
    pullPolicy: Always
    nexus3: nexus3-docker
  env:
    lsstDdsPartitionPrefix: tucson
    brokerIp: cp-helm-charts-cp-kafka-headless.cp-helm-charts
    brokerPort: 9092
    registryAddr: http://cp-helm-charts-cp-schema-registry.cp-helm-charts:8081
    partitions: 1
    replication: 3
    waitAck: 1
    logLevel: 20
    extras:
      LSST_DDS_RESPONSIVENESS_TIMEOUT: 15s
  shmemDir: /run/ospl
  producers:
    eas:
      cscs: DIMM DSM WeatherStation
    mtaircompressor:
      cscs: MTAirCompressor
  osplVersion: V6.10.4
  startupProbe:
    use: true
    failureThreshold: 15
    initialDelay: 20
    period: 10
