csc:
  image:
    repository: ts-dockerhub.lsst.org/scheduler
    tag: c0021
    pullPolicy: Always
    nexus3: nexus3-docker
  env:
    LSST_DDS_PARTITION_PREFIX: summit
  shmemDir: /run/ospl
  osplVersion: V6.10.4
  nfsMountpoint:
  - name: rubin-sim-data
    containerPath: /home/saluser/rubin_sim_data
    readOnly: true
    server: nfs1.cp.lsst.org
    serverPath: /scratch/scheduler
