csc:
  image:
    repository: ts-dockerhub.lsst.org/scheduler
    tag: c0024
    pullPolicy: Always
    nexus3: nexus3-docker
  env:
    LSST_DDS_PARTITION_PREFIX: tucson
    S3_ENDPOINT_URL: https://s3.tu.lsst.org
  envSecrets:
  - name: AWS_ACCESS_KEY_ID
    secretName: lfa
    secretKey: aws-access-key-id
  - name: AWS_SECRET_ACCESS_KEY
    secretName: lfa
    secretKey: aws-secret-access-key
  - name: MYS3_ACCESS_KEY
    secretName: lfa
    secretKey: aws-access-key-id
  - name: MYS3_SECRET_KEY
    secretName: lfa
    secretKey: aws-secret-access-key
  shmemDir: /run/ospl
  osplVersion: V6.10.4
  nfsMountpoint:
  - name: rubin-sim-data
    containerPath: /home/saluser/rubin_sim_data
    readOnly: true
    server: nfs-scratch.tu.lsst.org
    serverPath: /scratch/scheduler
