csc: 
  image:
    repository: ts-dockerhub.lsst.org/test
    tag: c0022
    pullPolicy: Always
    nexus3: nexus3-docker
  env:
    LSST_DDS_PARTITION_PREFIX: base
  osplVersion: V6.10.4
  shmemDir: /run/ospl
