apiVersion: v1
kind: Service
metadata:
  labels:
    csc: {{ .Release.Name }}
  name: {{ .Release.Name }}-service
  namespace: {{ .Values.csc.namespace }}
spec:
  ports:
  - port: {{ .Values.port }}
    targetPort: {{ .Values.port }}
  selector:
    csc: {{ .Release.Name }}
  type: ClusterIP
