# -- Set the replica count for the ts_audio_broadcasters
replicaCount: 1
# -- The overall namespace for the ts_audio_broadcaster
namespace: love
image:
  # -- The ts_audio_broadcaster image to use
  repository: lsstts/audio-broadcaster
  # -- The tag to use for the ts_audio_broadcaster image
  tag: develop
  # -- The pull policy on the ts_audio_broadcaster image
  pullPolicy: IfNotPresent
  # -- The tag name for the Nexus3 Docker repository secrets if private images need to be pulled
  nexus3: nexus3-docker
# -- This section holds a set of key, value pairs for environmental variables
env:
  WEBSERVER_PORT: 8888
# -- This sections sets the list of producers to use.
# The microphones should be specified like:
# _name_:
# _host_: _Microphone host_
# _port_: _Microphone port_
# Example: auxtel1:
# host: localhost
# port: 4444
microphones: {}
# -- This allows the specification of pod annotations.
podAnnotations: {}
# -- Resource specifications for the ts_audio_broadcaster pods
resources: {}
# -- Node selection rules for the ts_audio_broadcaster pods
nodeSelector: {}
# -- Toleration specifications for the ts_audio_broadcaster pods
tolerations: []
# -- Affinity rules for the ts_audio_broadcaster pods
affinity: {}
