csc:
  image:
    repository: ts-dockerhub.lsst.org/headerservice
    tag: ts-v2.8.0_salobj_v6.2.0_idl_v2.3.0_xml_v7.1.0
    pullPolicy: Always
    nexus3: nexus3-docker
  env:
    LSST_DDS_PARTITION_PREFIX: summit
    IP_HEADERSERVICE: ccheaderservice.cp.lsst.org
    URL_SPEC: --url_format http://{ip_address}/{filename_HDR}
  mountpoint:
  - name: www
    path: /home/saluser/www
    accessMode: ReadWriteOnce
    claimSize: 50Gi
  shmemDir: /run/ospl
ingress:
  use: true
  hostname: ccheaderservice.cp.lsst.org
  port: 8000
