csc: 
  image:
    repository: ts-dockerhub.lsst.org/headerservice
    tag: ts-v2.5.1_salobj_v6.0.3_idl_v2.1.0_xml_v6.2.1
    pullPolicy: Always
    nexus3: nexus3-docker
  env:
    LSST_DDS_PARTITION_PREFIX: base
    IP_HEADERSERVICE: wangulen.ls.lsst.org
  entrypoint: |
    #!/usr/bin/env bash

    echo "# Starting CCHeaderService CSC"
  
    source start_CCHeaderService.sh

  mountpoint:
    - name: www
      path: /home/saluser/www
      accessMode: ReadWriteOnce
      claimSize: 50Gi
  shmemDir: /run/ospl
ingress:
  use: true
  hostname: wangulen.ls.lsst.org
