# Deployment at NCSA is handled by docker-compose for M1M3
# This is here as an emergency
csc:
  image:
    repository: ts-dockerhub.lsst.org/mtm1m3_sim
    tag: c0015
    pullPolicy: Always
    nexus3: nexus3-docker
  env:
    LSST_DDS_PARTITION_PREFIX: ncsa
