name: Deployment

on:
  push:
    paths:
      - "docs/**"

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install dependencies
        run: pip install -r docs/requirements.txt

      - name: Check links
        run: |
          cd docs
          make linkcheck

      - name: Build site
        run: |
          cd docs
          make html

      - name: Upload to LSST the Docs
        if: ${{ github.event_name == 'push' }}
        env:
          LTD_USERNAME: ${{ secrets.LTD_USERNAME }}
          LTD_PASSWORD: ${{ secrets.LTD_PASSWORD }}
        run: ltd upload --product argocd-csc --gh --dir docs/_build/html
