namespace: obssys
image:
  repository: ts-dockerhub.lsst.org/scriptqueue
  tag: c0026
  pullPolicy: Always
  nexus3: nexus3-docker
env:
  LSST_DDS_PARTITION_PREFIX: base
shmemDir: /run/ospl
osplVersion: V6.10.4
