csc:
  image:
    repository: ts-dockerhub.lsst.org/scriptqueue
    tag: c0023
    pullPolicy: Always
    nexus3: nexus3-docker
  env:
    LSST_DDS_PARTITION_PREFIX: ncsa
    RUN_ARG: 2 --state enabled
  shmemDir: /scratch.local/ospl
  nfsMountpoint:
  - name: auxtel-gen2
    containerPath: /project/shared/auxTel
    readOnly: true
    server: lsst-l1-cl-arctl.ncsa.illinois.edu
    serverPath: /project/shared/auxTel
  - name: lsstdata-teststand
    containerPath: /lsstdata/offline/teststand
    readOnly: false
    server: lsst-nfs.ncsa.illinois.edu
    serverPath: /offline/teststand
  - name: lsstdata-instrument
    containerPath: /lsstdata/offline/instrument
    readOnly: false
    server: lsst-nfs.ncsa.illinois.edu
    serverPath: /offline/instrument
  - name: gen3
    containerPath: /repo
    readOnly: false
    server: lsst-l1-cl-arctl.ncsa.illinois.edu
    serverPath: /repo
  osplVersion: V6.10.4
