csc:
  image:
    repository: ts-dockerhub.lsst.org/scriptqueue
    tag: c0021
    pullPolicy: Always
    nexus3: nexus3-docker
  env:
    LSST_DDS_PARTITION_PREFIX: ncsa
    RUN_ARG: 2
  shmemDir: /scratch.local/ospl
  nfsMountpoint:
  - name: lsstdata
    containerPath: /lsstdata/offline/teststand
    readOnly: true
    server: lsst-nfs.ncsa.illinois.edu
    serverPath: /offline/teststand
  osplVersion: V6.10.4
