csc:
  image:
    repository: ts-dockerhub.lsst.org/at_pneumatics_sim
    tag: c0011
    pullPolicy: Always
    nexus3: nexus3-docker
  env:
    LSST_DDS_DOMAIN: ncsa.obs.at.cs
    OSPL_INFOFILE: /tmp/ospl-info-atpneumatics.log
    OSPL_ERRORFILE: /tmp/ospl-error-atpneumatics.log
  osplVersion: V6.10.4
  shmemDir: /scratch.local/ospl
